### ISSUE TITLE
Python 3.8 daemon error

### ISSUE THREAD

**Issue by Blicklicht** [rorr73/LifeSOSpy_MQTT#15]
Hi,
i am running this on a Synology DS since years without any issue.
I think recently my Python got updated and I am getting the below error...

root@SNAS10TB:/volume1/@appstore/py3k/usr/local/bin# /volume1/@appstore/py3k/usr/local/bin/lifesospy_mqtt -w /volume1/SmartHome/LifeSOS/ -d -l -p
lifesospy_mqtt v0.11.5 - MQTT client to report state of LifeSOS security system and devices.

Starting daemon.
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/bin/lifesospy_mqtt", line 8, in <module>
    sys.exit(main())
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/lifesospy_mqtt/__main__.py", line 124, in main
    with daemon.DaemonContext(
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/daemon/daemon.py", line 280, in __init__
    detach_process = is_detach_process_context_required()
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/daemon/daemon.py", line 801, in is_detach_process_context_required
    if is_process_started_by_init() or is_process_started_by_superserver():
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/daemon/daemon.py", line 778, in is_process_started_by_superserver
    if is_socket(stdin_fd):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/daemon/daemon.py", line 743, in is_socket
    file_socket = socket.fromfd(fd, socket.AF_INET, socket.SOCK_RAW)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/socket.py", line 544, in fromfd
    return socket(family, type, proto, nfd)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 88] Socket operation on non-socket

Any idea how to solve this?
Thanks

**Comment by Blicklicht** [comment]
Issue is existing in version 3.8.2 but still running with 3.7.7

**Comment by rorr73** [comment]
@Blicklicht Thanks for finding and reporting this issue. I've reproduced it, and updated one of the dependencies that was causing the issue. If you upgrade to 0.11.6 it should be resolved.
